language: python
env:
  global:
  - secure: MTnYx1wJLTvPLBpY4O2Ia8P7RDXA7ICqqCUA6PsE03pSBzhtgXHm41/klnj96FB9EWIHcz4jWjPplgPBeVs+VCyn0NJberi/DVQsSs3KcVroKykVxIduWbvjbmx29QE3Id8RpPOuOr8pmBzeFVzwu7c2vthGjl7H9eJfKU1BphI=
  - secure: MwVYyHzysBxqcaHroOIv09T/ufww8pLG2ZIYGbFEfj4gumPpOIGcn0mFjnFqyQZykK2Epv3Yy0q6ChunhJuIYCv9jpGbMg5oBwV5KnMeyxXeB8EqcRsP+XSEn6Q+TXfZV0K/pjoBEM9uktJWS6EYFjTIEU0eZPgzsxmXrAG/UBI=
  - BOB_UPLOAD_WHEEL=1
matrix:
  include:
  - python: 2.7
    env:
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
  - python: 3.3
  - python: 3.4
  - python: 3.5
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes wget git-core pkg-config cmake python-dev python-support liblapack-dev libatlas-base-dev libblitz1-dev libavformat-dev libavcodec-dev libswscale-dev libboost-all-dev libmatio-dev libjpeg8-dev libnetpbm10-dev libpng12-dev libtiff4-dev libgif-dev libhdf5-serial-dev libfftw3-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended libsvm-dev libvl-dev dvipng python-numpy python-scipy dvipng libopencv-dev gfortran libsox-dev
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --egg --use-wheel sphinx nose numpy matplotlib coverage cpp-coveralls scipy nose-exclude
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --egg --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- CPPFLAGS=--coverage LDFLAGS=--coverage ./bin/buildout buildout:debug=false buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob.utils import get_config; print(get_config())'
- ./bin/coverage run --source=bob ./bin/nosetests bob bob.ip bob.learn.activation bob.learn.mlp bob.learn.libsvm bob.learn.linear bob.learn.em bob.io bob.blitz bob.ap bob.core bob.math bob.sp bob.measure -sv --first-package-wins
#- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
#- cpp-coveralls --build-root=`pwd` --exclude=src --exclude-pattern=".*Compiler.*" --dump=cpp_cov.json
#- coveralls --merge=cpp_cov.json
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
